生活福祉資金貸付制度のフロントエンドを追加
project-inclusive/OpenFisca-Japan pull request #40
Opened 2023-07-15 05:17 UTC by Syuparn

## 概要

- この Pull request は生活福祉資金貸付制度のフロントエンドを追加する
  - そのために フォームに 親または祖父母の入力欄 を追加した
  - そのために フォームに チェックボックス「家を借りたい」 を追加した
  - そのために 結果に生活福祉資金貸付制度の欄を追加

## 動作確認

- [x] 追加した部分の影響しそうな箇所を手動で動作確認した

![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/36665200/66fc316e-72c1-41cd-b693-ecc7fd45043a)

2023-07-15 05:24 UTC, Syuparn commented on dashboard/src/components/forms/attributes/LivingToghtherNum.tsx
> +          delete newHousehold.世帯員[name];
子育て支援制度では保護者一覧の「あなた」が使用されていたため、親に関するフォームではそれ以外の要素のみ扱うようにしています。

今後さらに `保護者一覧` の役割が増えたら、処理を簡潔にするため制度ごとに名称を変えて整理したほうが良いかもしれません...

2023-07-15 14:17 UTC, SnoozingJellyfish requested changes
プルリクありがとうございます！
いくつかコメントしているので、ご確認・修正お願いします。

2023-07-15 14:17 UTC, SnoozingJellyfish commented on dashboard/src/app_config.json
> +            "返済期限：終了時",
返済期限は「終了時」だけだと何の分からず、[厚労省HP](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsu-fukushi-shikin1/kashitsukejoken.html)の説明も理解できないので、ひとまず返済期限については記載しないで良いかと思います。分かりやすく説明しようとするとかなり行数が必要になりそうですし…。

2023-07-16 00:26 UTC, SnoozingJellyfish requested changes
コメント箇所が多く恐縮ですがご確認お願いします。

2023-07-16 00:26 UTC, SnoozingJellyfish commented on dashboard/src/app_config.json
> +            "生活再建までの間に一時的に必要な生活費用",
"生活再建までの間に一時的に必要な生活費用"は住宅入居費の説明にないので削除をお願いします。
"教育支援費"、"就学支度費"についても同様にお願いします。
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsu-fukushi-shikin1/kashitsukejoken.html

2023-07-16 00:26 UTC, SnoozingJellyfish commented on dashboard/src/components/loan.tsx
> +                        {val.displayedMoney} {val.unit}
- 算出される生活福祉資金貸付制度の貸付額は全て上限額のため、計算結果の金額の前に「〜」をつけてください。
- 生活福祉資金貸付制度の貸付上限額は全て1万円単位かつ額が大きいので、1の位まで表示するよりも「⚪︎⚪︎万円」と表記する方が分かりやすいかなと思います。給付金とフォーマットが異なりますが、異なるブロックなのであまり気にならないですかね…。
将来的に変わる可能性もありますが、現時点ではフロントエンド側で生活福祉資金貸付制度の貸付上限額を10000で割った値に「万円」をつけるのが良いように思います。

2023-07-16 03:07 UTC, Syuparn commented on dashboard/src/components/forms/attributes/LivingToghtherNum.tsx
> +          delete newHousehold.世帯員[name];
こちら「保護者」に設定しないと読み込めないと仕様を誤解していました...
祖父母のみのフィールドに分離したので、ひとり親の判定と干渉しないようになりました。

https://github.com/project-inclusive/OpenFisca-Japan/pull/40/commits/83889cba0b0849da70b1ad67e5a4d368fc5d801e

2023-07-16 03:09 UTC, Syuparn commented on dashboard/src/components/forms/parents.tsx
> +              </Box>
「親または祖父母」にも年収、学生の欄を追加しました。祖父母の年収が非課税基準の判定で参照されていることも確認済みです。

https://github.com/project-inclusive/OpenFisca-Japan/pull/40/commits/83889cba0b0849da70b1ad67e5a4d368fc5d801e

2023-07-16 03:18 UTC, Syuparn commented on dashboard/src/components/forms/parents.tsx
> +              </Box>
教育支援資金の説明では世帯の誰かが就学する場合に使えるとあります（子に限られるという記載は見当たらない）が、現在のバックエンドの計算式では子どもが就学する場合のみ対象となっています。

親、祖父母が就学する場合にも計算式に含めたほうが良いでしょうか？

https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/seikatsuhogo/seikatsu-fukushi-shikin1/kashitsukejoken.html
https://www.tcsw.tvac.or.jp/activity/documents/kyoikusiennsikinpannfu.pdf

2023-07-16 03:19 UTC, Syuparn commented on dashboard/src/components/forms/parents.tsx
> +  return (
フィールドを分けたことで10人以上生成されないようになりました。

2023-07-16 03:22 UTC, Syuparn commented on dashboard/src/components/loan.tsx
> +                    <br></br>
map内の改行と被ることを失念していました。改行を取り除き上下が分かれないようにしました。

![image](https://github.com/project-inclusive/OpenFisca-Japan/assets/36665200/05292e76-fef1-4703-bc35-3ed04df6b8c8)


https://github.com/project-inclusive/OpenFisca-Japan/pull/40/commits/ef55322cacca5c441aee679f68b372aaad901ece

2023-07-16 03:23 UTC, Syuparn commented on dashboard/src/app_config.json
> +            "返済期限：終了時",
おっしゃる通りこれだと内容が分からないので説明を省きました。

https://github.com/project-inclusive/OpenFisca-Japan/pull/40/commits/60cb2838a4f2b748ee8f3cf7c8682d52dd41a769

2023-07-16 03:25 UTC, Syuparn commented on dashboard/src/app_config.json
> +            "生活再建までの間に一時的に必要な生活費用",
別の項目の文言と混ざってしまっていました...
不要なので削除しました。

https://github.com/project-inclusive/OpenFisca-Japan/pull/40/commits/1861b16d8bae1efa6d53b99908ef0fbaee2b97f2

2023-07-16 03:32 UTC, Syuparn commented on dashboard/src/components/loan.tsx
> +                        {val.displayedMoney} {val.unit}
表示を `~xx万円` or `~xx万円/月` に整形しました。
1万円単位に整形するのはフロントエンド上の実装依存のため、configのunitではなく実装側に `万` 直接記載しました。
（将来単位を変える際の改修漏れを防ぐため）

https://github.com/project-inclusive/OpenFisca-Japan/pull/40/commits/d2e1baeffbfb8496d01431c13801755c3f1369c9

2023-07-16 03:36 UTC, Syuparn commented
@SnoozingJellyfish 
レビューありがとうございます。コメントいただいたところ修正しましたのでご確認お願いします。

2023-07-17 00:24 UTC, SnoozingJellyfish commented on dashboard/src/components/forms/parents.tsx
> +              </Box>
検討ありがとうございます。
「小・中・高校、大学、専門学校、職業訓練学校等の学生である」の項目は、児童手当等の所得を算出するための勤労学生控除判定に用いるため設定しています。
教育支援資金でも高校・高専・大学・短大は子でなくても対象となりますが、小・中・職業訓練学校は対象とならないので、項目を分ける必要があります。
ただ、教育支援資金を借りる世帯で大人が高校以上に通う例は少ないと考えられ、フォームも煩雑になることから、ひとまず子供の場合のみで考えようと思います。

2023-07-17 00:34 UTC, SnoozingJellyfish commented
修正ありがとうございます。動作確認できましたのでマージします。

2023-07-17 00:38 UTC, SnoozingJellyfish approved these changes
修正確認できました。

2023-07-17 00:39 UTC, merged

2023-07-17 11:25 UTC, Syuparn commented on dashboard/src/components/forms/parents.tsx
> +              </Box>
そういう背景があったのですね。承知しました。